create homepage
GSG-CF05/delivery-app-team11 pull request #14
Opened 2022-02-07 17:40 UTC by MohamedSatary

relates #13

2022-02-08 09:47 UTC, yaqootturman requested changes

2022-02-08 09:47 UTC, yaqootturman commented on index.html
> +    <nav>
use footer tag as a semantic element

2022-02-08 09:47 UTC, yaqootturman commented on index.html
> +        <a href="#">All</a>
make one of them highlight

2022-02-08 11:30 UTC, salwasiksik approved these changes

2022-02-09 07:44 UTC, yaqootturman approved these changes

2022-02-09 07:48 UTC, salwasiksik approved these changes

2022-02-09 08:08 UTC, bayan2002 approved these changes

2022-02-09 08:14 UTC, merged