2 create read me file
GSG-CF05/delivery-app-team11 pull request #4
Opened 2022-02-06 18:57 UTC by salwasiksik

2022-02-06 19:37 UTC, MohamedSatary approved these changes

2022-02-06 19:59 UTC, bayan2002 approved these changes

2022-02-06 20:01 UTC, yaqootturman approved these changes

2022-02-06 20:05 UTC, yaqootturman requested changes

2022-02-06 20:05 UTC, yaqootturman commented on README.md
> +## You can check it out [HERE](link of the page)
You can generate it since you have index.html in the root

2022-02-06 20:15 UTC, yaqootturman requested changes

2022-02-06 20:15 UTC, yaqootturman commented on README.md
> +## You can check it out [HERE](link of the page)
You can generate it since you have index.html in the root

2022-02-07 05:14 UTC, yaqootturman approved these changes

2022-02-07 08:09 UTC, merged